name: pipelines
on: workflow_dispatch #manually
jobs:
  buildApp:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Install Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'microsoft' # guessing az-devops also uses this
          architecture: 'x64'