name: pipelines
on: workflow_dispatch #manually
jobs:
  buildApp:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Install Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'microsoft' # guessing az-devops also uses this
          architecture: 'x64'
      - name: Node install
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'
      - name: Install Yarn
        uses: bahmutov/npm-install@v1
      - name: Install Yalc
        run:  yarn global add yalc@1.0.0-pre.50
      - name: Check versions
        run: |
            echo "Node version:"
            node --version
            echo "Java version:"
            java -version
            echo "yarn version:"
            yarn --version
            echo "yalc version:"
            yalc --version
